### ISSUE TITLE
以后不能使用clash了吗

### ISSUE THREAD

**Issue by BaiRiDreamer** [FlyShadowVPN/FlyShadowVPN#1]
现在复制订阅链接到clash已经无法使用了，怎么回事？

**Comment by FlyShadowVPN** [comment]
目前还在支持，需要手动把订阅参数修改成type=Clash

**Comment by WSMTBG** [comment]
> 目前还在支持，需要手动把订阅参数修改成type=Clash

请问怎么改这个，我在订阅链接最后加了&type=Clash，能获取节点但是全超时

**Comment by FlyShadowVPN** [comment]
> > 目前仍然支持，需要手动将订阅参数修改成type=Clash
> 
> 请问怎么改这个，我在订阅链接最后加了&type=Clash，能获取节点但是全超时
修改得没错，现在节点一切正常，如果有问题的话可以咨询官网的客服给你看下具体情况呢。
